name: Deploy React App

on:
  push:
    branches:
      - main  # deploy on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install dependencies (in VolleyStats folder)
      - name: Install dependencies
        run: npm ci || npm install
        working-directory: ./VolleyStats

      # 4. Build the React app
      - name: Build React app
        run: npm run build
        working-directory: ./VolleyStats

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./VolleyStats/build
